
title: Gabriel Dwyer
email: gpcdwyer@gmail.com
description: >-
  Failing Polymath
baseurl: ""
url: ""
twitter_username: gabriel_dwyer
github_username:  gabrieldwyer
linkedin_username: my linkedin account

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Google Analytics
google_analytics: UA-67193322-1
